name: Update wallpaper

on:
  schedule:
    - cron: "*/30 * * * *"   # toutes les 30 minutes
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Generate image
        env:
          CHANNEL: ${{ secrets.CHANNEL }}
          GOAL: "10000"
          W: "1170"
          H: "2532"
        run: |
          python generate.py

      - name: Commit wallpaper
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add wallpaper.png
          git commit -m "Update wallpaper" || echo "No changes"
          git push
